import { JobProps, TaskProps, WorkflowProps } from "./objects";

export const sampleJobs: JobProps[] = [
  {
    pkkey: 1,
    code: "JOB-001",
    customerID: 101,
    customerName: "Acme Corp",
    siteID: 201,
    siteName: "HQ Building",
    address: "123 Main Street, Kuala Lumpur, Malaysia",
    title: "Install Security Cameras",
    type: "Processing",
    report: "",
    status: "Processing",
    startDate: "2025-08-10",
    assignTo: "John Doe",
    priority: "High",
    description: "Install 4 CCTV cameras in the main lobby."
  },
  {
    pkkey: 2,
    code: "JOB-002",
    customerID: 102,
    customerName: "Tech Solutions",
    siteID: 202,
    siteName: "Data Center",
    address: "45 Jalan Ampang, Kuala Lumpur, Malaysia",
    title: "Replace Door Locks",
    type: "Processing",
    report: "",
    status: "Processing",
    startDate: "2025-08-11",
    assignTo: "Jane Smith",
    priority: "Medium",
    description: "Replace faulty door locks in meeting rooms."
  },
  {
    pkkey: 3,
    code: "JOB-003",
    customerID: 103,
    customerName: "Green Energy Ltd.",
    siteID: 203,
    siteName: "Solar Plant #5",
    address: "Lot 9, Industrial Park, Penang, Malaysia",
    title: "Server Maintenance",
    type: "Approval",
    report: "Completed maintenance and updated server firmware.",
    status: "Completed",
    startDate: "2025-08-09",
    assignTo: "Alex Lee",
    priority: "Low",
    description: "Routine maintenance of server hardware."
  },
  {
    pkkey: 4,
    code: "JOB-004",
    customerID: 104,
    customerName: "Blue Ocean Shipping",
    siteID: 204,
    siteName: "Port Klang Office",
    address: "88 Harbour Road, Port Klang, Malaysia",
    title: "Network Upgrade",
    type: "Processing",
    report: "",
    status: "Processing",
    startDate: "2025-08-12",
    assignTo: "Samuel Tan",
    priority: "High",
    description: "Upgrade office network infrastructure to 10Gbps."
  },
  {
    pkkey: 5,
    code: "JOB-005",
    customerID: 105,
    customerName: "Skyline Towers",
    siteID: 205,
    siteName: "Tower B",
    address: "25 Jalan Sultan Ismail, Kuala Lumpur, Malaysia",
    title: "Air Conditioning Repair",
    type: "Processing",
    report: "",
    status: "Processing",
    startDate: "2025-08-13",
    assignTo: "Maria Lim",
    priority: "Medium",
    description: "Repair faulty air conditioning unit in lobby."
  },
  {
    pkkey: 6,
    code: "JOB-006",
    customerID: 106,
    customerName: "City Hospital",
    siteID: 206,
    siteName: "Main Wing",
    address: "101 Jalan Tun Razak, Kuala Lumpur, Malaysia",
    title: "Fire Alarm Inspection",
    type: "Approval",
    report: "All fire alarms inspected and tested successfully.",
    status: "Completed",
    startDate: "2025-08-08",
    assignTo: "David Wong",
    priority: "Low",
    description: "Annual inspection of fire alarm systems."
  },
  {
    pkkey: 7,
    code: "JOB-007",
    customerID: 107,
    customerName: "Sunrise Hotel",
    siteID: 207,
    siteName: "Resort Wing",
    address: "Beach Road, Langkawi, Malaysia",
    title: "WiFi Access Point Installation",
    type: "Processing",
    report: "",
    status: "Processing",
    startDate: "2025-08-14",
    assignTo: "Lily Chan",
    priority: "High",
    description: "Install 10 WiFi access points for guest areas."
  },
  {
    pkkey: 8,
    code: "JOB-008",
    customerID: 108,
    customerName: "Global Foods",
    siteID: 208,
    siteName: "Warehouse 3",
    address: "Lot 20, Industrial Zone, Johor Bahru, Malaysia",
    title: "Cold Storage Repair",
    type: "Processing",
    report: "",
    status: "Processing",
    startDate: "2025-08-15",
    assignTo: "Henry Goh",
    priority: "High",
    description: "Repair temperature control system in cold storage."
  },
  {
    pkkey: 9,
    code: "JOB-009",
    customerID: 109,
    customerName: "Metro Mall",
    siteID: 209,
    siteName: "Main Mall",
    address: "1 Jalan Imbi, Kuala Lumpur, Malaysia",
    title: "Escalator Maintenance",
    type: "Approval",
    report: "Routine escalator check completed.",
    status: "Completed",
    startDate: "2025-08-07",
    assignTo: "Alan Tan",
    priority: "Medium",
    description: "Monthly maintenance of all escalators."
  },
  {
    pkkey: 10,
    code: "JOB-010",
    customerID: 110,
    customerName: "Petronas Towers",
    siteID: 210,
    siteName: "Tower 1",
    address: "Kuala Lumpur City Centre, Malaysia",
    title: "Elevator Upgrade",
    type: "Processing",
    report: "",
    status: "Processing",
    startDate: "2025-08-16",
    assignTo: "Noraini Hassan",
    priority: "High",
    description: "Upgrade elevator control systems."
  }
];

export const sampleWorkflowData: WorkflowProps[] = [
  {
    pkkey: 1,
    code: "WF-001",
    description: "Purchase order for raw materials",
    productSeries: "Series-A",
    productStage: "Initial",
    status: "Pending",
    totalAmount: "1500.00",
    currencyName: "USD",
    remark: "Urgent order",
    requester: "Alice Johnson",
    dueDate: "2025-08-20",
    supplierName: "Global Supplies Ltd.",
    movementType: "Import",
    debitAccount: "ACC-1001",
    shipping: "Air Freight",
    getDate: "2025-08-18",
    createdDate: "2025-08-10",
  },
  {
    pkkey: 2,
    code: "WF-002",
    description: "Laptop procurement for new employees",
    productSeries: "Series-B",
    productStage: "Approval",
    status: "Approved",
    totalAmount: "5600.00",
    currencyName: "MYR",
    remark: "For IT department",
    requester: "Brian Lee",
    dueDate: "2025-08-22",
    supplierName: "TechWorld",
    movementType: "Local Purchase",
    debitAccount: "ACC-1002",
    shipping: "Courier",
    getDate: "2025-08-17",
    createdDate: "2025-08-11",
  },
  {
    pkkey: 3,
    code: "WF-003",
    description: "Office renovation materials",
    productSeries: "Series-C",
    productStage: "In Progress",
    status: "Ongoing",
    totalAmount: "20000.00",
    currencyName: "SGD",
    remark: "Phase 1 works",
    requester: "Chloe Tan",
    dueDate: "2025-09-01",
    supplierName: "BuildCo",
    movementType: "Local Purchase",
    debitAccount: "ACC-1003",
    shipping: "Truck Delivery",
    getDate: "2025-08-19",
    createdDate: "2025-08-12",
  },
  {
    pkkey: 4,
    code: "WF-004",
    description: "Annual software license renewal",
    productSeries: "Series-D",
    productStage: "Completed",
    status: "Closed",
    totalAmount: "7500.00",
    currencyName: "USD",
    remark: "Renewal for all users",
    requester: "David Wong",
    dueDate: "2025-08-25",
    supplierName: "SoftWareHub",
    movementType: "Online Purchase",
    debitAccount: "ACC-1004",
    shipping: "N/A",
    getDate: "2025-08-18",
    createdDate: "2025-08-13",
  },
  {
    pkkey: 5,
    code: "WF-005",
    description: "Procurement of lab equipment",
    productSeries: "Series-E",
    productStage: "Verification",
    status: "Under Review",
    totalAmount: "12000.00",
    currencyName: "EUR",
    remark: "High priority for R&D",
    requester: "Evelyn Smith",
    dueDate: "2025-08-28",
    supplierName: "LabTech",
    movementType: "Import",
    debitAccount: "ACC-1005",
    shipping: "Sea Freight",
    getDate: "2025-08-20",
    createdDate: "2025-08-14",
  },
  {
    pkkey: 6,
    code: "WF-006",
    description: "Marketing campaign materials",
    productSeries: "Series-F",
    productStage: "Planning",
    status: "Draft",
    totalAmount: "3000.00",
    currencyName: "GBP",
    remark: "For upcoming product launch",
    requester: "Frank Wilson",
    dueDate: "2025-09-05",
    supplierName: "Print & Co",
    movementType: "Local Purchase",
    debitAccount: "ACC-1006",
    shipping: "Courier",
    getDate: "2025-08-21",
    createdDate: "2025-08-15",
  },
];

export const sampleTaskData: TaskProps[] = [
  {
    pkkey: 1,
    code: "TSK-001",
    title: "Prepare purchase order",
    status: "Pending",
    type: "Procurement",
  },
  {
    pkkey: 2,
    code: "TSK-002",
    title: "Review supplier contract",
    status: "In Progress",
    type: "Legal",
  },
  {
    pkkey: 3,
    code: "TSK-003",
    title: "Approve budget request",
    status: "Approved",
    type: "Finance",
  },
  {
    pkkey: 4,
    code: "TSK-004",
    title: "Schedule delivery",
    status: "Ongoing",
    type: "Logistics",
  },
  {
    pkkey: 5,
    code: "TSK-005",
    title: "Verify stock quantity",
    status: "Completed",
    type: "Inventory",
  },
  {
    pkkey: 6,
    code: "TSK-006",
    title: "Send invoice to client",
    status: "Draft",
    type: "Billing",
  },
];

export const SampleTask = {
  "taskList": [
    {
      "pkkey": 1,
      "code": "MAT-001",
      "description": "Purchase raw materials",
      "productSeries": "Series A",
      "productStage": "Initial",
      "status": "Pending",
      "totalAmount": "1500",
      "currencyName": "USD",
      "remark": "Urgent requirement",
      "requester": "John Doe",
      "dueDate": "2025-08-20",
      "supplierName": "ABC Supplies",
      "movementType": "Purchase",
      "debitAccount": "5001",
      "shipping": "Air Freight",
      "getDate": "2025-08-18",
      "createdDate": "2025-08-10"
    },
    {
      "pkkey": 2,
      "code": "MAT-002",
      "description": "Order spare parts",
      "productSeries": "Series B",
      "productStage": "Production",
      "status": "Approved",
      "totalAmount": "2300",
      "currencyName": "EUR",
      "remark": "For urgent machine repair",
      "requester": "Jane Smith",
      "dueDate": "2025-08-22",
      "supplierName": "XYZ Parts Co.",
      "movementType": "Transfer",
      "debitAccount": "5002",
      "shipping": "Sea Freight",
      "getDate": "2025-08-19",
      "createdDate": "2025-08-11"
    },
    {
      "pkkey": 3,
      "code": "MAT-003",
      "description": "Chemical solvents",
      "productSeries": "Series C",
      "productStage": "Testing",
      "status": "In Progress",
      "totalAmount": "850",
      "currencyName": "MYR",
      "remark": "Need by next week",
      "requester": "Michael Lee",
      "dueDate": "2025-08-25",
      "supplierName": "ChemWorld",
      "movementType": "Purchase",
      "debitAccount": "5003",
      "shipping": "Courier",
      "getDate": "2025-08-17",
      "createdDate": "2025-08-12"
    },
    {
      "pkkey": 4,
      "code": "MAT-004",
      "description": "Office chairs",
      "productSeries": "Series D",
      "productStage": "Procurement",
      "status": "Rejected",
      "totalAmount": "1200",
      "currencyName": "USD",
      "remark": "Budget exceeded",
      "requester": "Anna Tan",
      "dueDate": "2025-08-30",
      "supplierName": "FurniCo",
      "movementType": "Purchase",
      "debitAccount": "5004",
      "shipping": "Land Transport",
      "getDate": "2025-08-21",
      "createdDate": "2025-08-13"
    },
    {
      "pkkey": 5,
      "code": "MAT-005",
      "description": "IT equipment upgrade",
      "productSeries": "Series E",
      "productStage": "Deployment",
      "status": "Completed",
      "totalAmount": "4500",
      "currencyName": "USD",
      "remark": "Approved by IT",
      "requester": "Samuel Wong",
      "dueDate": "2025-09-01",
      "supplierName": "TechZone",
      "movementType": "Purchase",
      "debitAccount": "5005",
      "shipping": "Express",
      "getDate": "2025-08-18",
      "createdDate": "2025-08-14"
    },
    {
      "pkkey": 6,
      "code": "MAT-006",
      "description": "Packaging materials",
      "productSeries": "Series F",
      "productStage": "Final",
      "status": "Pending",
      "totalAmount": "600",
      "currencyName": "SGD",
      "remark": "For new product launch",
      "requester": "Diana Lim",
      "dueDate": "2025-08-27",
      "supplierName": "PackIt Co.",
      "movementType": "Purchase",
      "debitAccount": "5006",
      "shipping": "Standard",
      "getDate": "2025-08-20",
      "createdDate": "2025-08-15"
    },
        {
      "pkkey": 7,
      "code": "MAT-007",
      "description": "Lab safety equipment",
      "productSeries": "Series G",
      "productStage": "Quality",
      "status": "Approved",
      "totalAmount": "3100",
      "currencyName": "USD",
      "remark": "For new lab setup",
      "requester": "Kevin Chan",
      "dueDate": "2025-09-03",
      "supplierName": "SafeLab Ltd.",
      "movementType": "Purchase",
      "debitAccount": "5007",
      "shipping": "Air Cargo",
      "getDate": "2025-08-22",
      "createdDate": "2025-08-16"
    },
    {
      "pkkey": 8,
      "code": "MAT-008",
      "description": "Marketing brochures",
      "productSeries": "Series H",
      "productStage": "Promotion",
      "status": "Pending",
      "totalAmount": "950",
      "currencyName": "MYR",
      "remark": "Needed for upcoming expo",
      "requester": "Elaine Goh",
      "dueDate": "2025-08-28",
      "supplierName": "PrintWorks",
      "movementType": "Service",
      "debitAccount": "5008",
      "shipping": "Courier",
      "getDate": "2025-08-21",
      "createdDate": "2025-08-17"
    }
  ]
}

export const SampleMessage = {
  "messageList": [
    {
      "id": 1,
      "Title": "System Maintenance",
      "Description": "The system will be down for maintenance from 12:00 AM to 3:00 AM.",
      "Date": "2025-03-05",
      "status": 1
    },
    {
      "id": 2,
      "Title": "New Feature Released",
      "Description": "We have launched a new dark mode feature for better user experience.",
      "Date": "2025-03-04",
      "status": 2
    },
    {
      "id": 3,
      "Title": "Security Alert",
      "Description": "Please update your password to ensure account security.",
      "Date": "2025-03-03",
      "status": 1
    },
    {
      "id": 4,
      "Title": "Holiday Notice",
      "Description": "Our offices will be closed on March 10th for a public holiday.",
      "Date": "2025-03-02",
      "status": 0
    }
  ]
}

export const SampleAcknowledge = {
  "acknowledgeList": [
    {
      "id": 1,
      "SerialNumber": "SN123456",
      "VehicleNo": "ABC1234",
      "Date": "2024-03-07T10:30:00Z",
      "status": 1
    },
    {
      "id": 2,
      "SerialNumber": "SN654321",
      "VehicleNo": "XYZ5678",
      "Date": "2024-03-06T15:45:00Z",
      "status": 0
    },
    {
      "id": 3,
      "SerialNumber": "SN789012",
      "VehicleNo": "DEF4321",
      "Date": "2024-03-05T08:20:00Z",
      "status": 2
    },
    {
      "id": 4,
      "SerialNumber": "SN345678",
      "VehicleNo": "GHI8765",
      "Date": "2024-03-04T12:10:00Z",
      "status": 1
    }
  ]  
}

